use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let config_path = "www/config/player-defaults.json";
    println!("cargo:rerun-if-changed={config_path}");

    let json_str = fs::read_to_string(config_path)
        .unwrap_or_else(|e| panic!("Failed to read {config_path}: {e}"));

    let config: serde_json::Value =
        serde_json::from_str(&json_str).unwrap_or_else(|e| panic!("Invalid JSON in {config_path}: {e}"));

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("defaults_generated.rs");

    let gain = config["gain_comp_amount"].as_f64().unwrap_or(0.5);
    let mid_side = config["mid_side_mode"].as_bool().unwrap_or(true);
    let phase_lock = config["phase_lock"].as_bool().unwrap_or(false);
    let transient = config["transient_detect"].as_bool().unwrap_or(false);
    let cubic = config["cubic_resampler"].as_bool().unwrap_or(false);
    let limiter = config["soft_limiter"].as_bool().unwrap_or(false);
    let sensitivity = config["transient_sensitivity"].as_f64().unwrap_or(0.5);

    let code = format!(
        r#"// AUTO-GENERATED by build.rs from www/config/player-defaults.json
// Do not edit manually.
pub const DEFAULT_GAIN_COMP_AMOUNT: f64 = {gain};
pub const DEFAULT_MID_SIDE_MODE: bool = {mid_side};
pub const DEFAULT_PHASE_LOCK: bool = {phase_lock};
pub const DEFAULT_TRANSIENT_DETECT: bool = {transient};
pub const DEFAULT_CUBIC_RESAMPLER: bool = {cubic};
pub const DEFAULT_SOFT_LIMITER: bool = {limiter};
pub const DEFAULT_TRANSIENT_SENSITIVITY: f64 = {sensitivity};
"#
    );

    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {e}", dest.display()));
}
